server:
 port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  tracing:
    sampling:
      probability: 1.0
spring:
  #JDBC
  datasource:
    url: jdbc:mysql://localhost:3306/transactionProcessingSystem
    username: root
    password: Balajisai@1234#
  #hibernate (JPA)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: sampleworktest5@gmail.com
    password: sbdf gekk brbw yrxi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #kafka config & Producer serialization
  kafka:
    bootstrap:
      servers: 9093
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
       spring.json.trusted.packages: "*"
  