spring:
  application:
    name: transaction-api-gateway
  config:
    import: "configserver:http://localhost:8088"
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: account-service
            uri: lb://account-service
            predicates:
            - Path=/account/**
          - id: transaction-service
            uri: lb://transaction-service
            predicates:
            - Path=/transaction/**
          - id: audit-service
            uri: lb://audit-service
            predicates:
            - Path=/audit/**
          - id: fraud-service
            uri: lb://fraud-service
            predicates:
            - Path=/fraud/**
          - id: notification-service
            uri: lb://notification-service
            predicates:
            - Path=/notification/**
